# install http client extention
@url_dev= http://localhost:3052/v1/api/

### signup
POST {{url_dev}}shop/signup
Content-Type: application/json
x-api-key: f018f5133e3bea5639f0925f236edd3b403f11cc2838ba3cd908ed7fface1bd7f7417d4620cd9baf5559755bb158ac3325da5f546ce5af5151b3b3e9eead4c3c

{
    "name" : "Shop Dev",
    "email" : "shopdev03@gmail.com",
    "password" : "abc123"
}
